create table hibernate_sequence (
    next_val bigint
) ;

insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );

CREATE TABLE user_entity (
                      id BIGINT NOT NULL generated by default as identity,
                      password varchar(64) not null,
                      username varchar(64) not null unique,
                      PRIMARY KEY (id)
);

CREATE TABLE todo (
                      id BIGINT NOT NULL generated by default as identity,
                      title varchar(64) not null,
                      completed BOOLEAN NOT NULL,
                      PRIMARY KEY (id)
) ;