create table answer
(
    id           int8 not null,
    answer_order int4,
    question_id  int8,
    text         varchar(10000000),
    primary key (id)
);
create table lessons
(
    id       int8 not null,
    theme_id int8,
    text     varchar(10485760),
    primary key (id)
);
create table question
(
    id             int8 not null,
    question_order int4,
    test_id        int8,
    text           varchar(10485760),
    primary key (id)
);
create table test
(
    id   int8 not null,
    name varchar(10485760),
    primary key (id)
);
create table test_users
(
    id           int8 not null,
    answer_id      int8,
    created_at   timestamp,
    test_id      int8,
    user_user_id int8,
    primary key (id)
);
create table theme
(
    id   int8 not null,
    name varchar(255),
    primary key (id)
);
create table todo
(
    id          int8 generated by default as identity,
    completed   boolean,
    description varchar(255),
    title       varchar(255),
    user_id     int8,
    primary key (id)
);
create table users_entity
(
    user_id     int8 generated by default as identity,
    birthday    timestamp,
    email       varchar(255),
    enabled     boolean,
    last_name   varchar(255),
    locked      boolean,
    login       varchar(255),
    middle_name varchar(255),
    name        varchar(255),
    password    varchar(255),
    role        varchar(255),
    lesson_id   int8,
    primary key (user_id)
);

create sequence hibernate_sequence start 1 increment 1;
