version: '3'

services:

  file-sharing-service:
    image: file-sharing-service:0.0.1-SNAPSHOT
    build:
      context: .
    container_name: file_sharing_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shar_db
    depends_on:
       - db
    ports:
       - "8088:8088"

  db:
    image: postgres:12
    container_name: file_sharing_db
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: rttr
      POSTGRES_DB: shar_db
    ports:
      - "5432:5432"

volumes:
  db-data:
    driver: local