version: '3'

services:

  web-app-service:
    image: web-app-service:0.0.1-SNAPSHOT
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-app-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shar_db
    depends_on:
      - db
    ports:
      - "8088:8088"

  dictionary-service:
    image: dictionary-service:0.0.1-SNAPSHOT
    build:
      context: ../english-lessons-dictionary/
      dockerfile: Dockerfile
    container_name: dictionary-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db2:5400/shar_db2
      SPRING_DOCKER_URL: web-app-service
    depends_on:
      - db2
      - web-app-service
    ports:
      - "8087:8087"

  db:
    image: postgres:12
    container_name: web_app_db
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: rttr
      POSTGRES_DB: shar_db
    ports:
      - "5432:5432"

  db2:
    image: postgres:12
    container_name: web_app_db2
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: rttr
      POSTGRES_DB: shar_db2
    ports:
      - "5400:5432"

volumes:
  db-data:
    driver: local