DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS operations CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS category CASCADE;

create table accounts
(
    account_id uuid not null,
    balance numeric(19, 2) not null,
    user_id int8 not null,
    primary key (account_id)

);
create table category
(
    income_or_expense int4 not null,
    category_id uuid not null,
    action_type varchar(255) not null,
    primary key (category_id)
);
create table operations
(
    operation_id uuid not null,
    amount numeric(19, 2) not null,
    date timestamp not null,
    type varchar(255) not null,
    account_id uuid not null,
    category_id uuid not null,
    primary key (operation_id)
);
create table users
(
    user_id int8 generated by default as identity,
    name varchar(255) not null,
    phone_number varchar(255) not null,
    primary key (user_id)
);

ALTER TABLE IF EXISTS users ADD CONSTRAINT _UNIQUEKEY_INDEX_1 UNIQUE (phone_number);
ALTER TABLE IF EXISTS  category ADD CONSTRAINT _UNIQUEKEY_INDEX_2 UNIQUE (action_type);
ALTER TABLE IF EXISTS accounts ADD CONSTRAINT _UNIQUEKEY_INDEX_3 FOREIGN KEY (user_id) REFERENCES users;
ALTER TABLE IF EXISTS operations ADD CONSTRAINT _UNIQUEKEY_INDEX_4 FOREIGN KEY (account_id) REFERENCES accounts;
ALTER TABLE IF EXISTS operations ADD CONSTRAINT _UNIQUEKEY_INDEX_5 FOREIGN KEY (category_id) REFERENCES category;
ALTER TABLE accounts ALTER COLUMN account_id SET DEFAULT uuid_in((md5((random())::text))::cstring);
INSERT INTO users(user_id,name, phone_number) VALUES
(1,'Anna','+380997548625'),
(2,'Jek','+38099754111'),
(3,'Bob','+380997111625');

INSERT INTO accounts(balance, user_id) VALUES
( 1000.00, 1),
( 2000.00, 1),
( 3000.00, 2);


