server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5400/db_final
    driver-class-name: org.postgresql.Driver
    username: rttr
    password: root
  jpa:
   generate-ddl: true
   show-sql: true
   hibernate:
    ddl-auto: update


#spring.jpa.hibernate.ddl-auto=create-drop


## swagger
#api.version=1.0
#swagger.enabled=true
#swagger.title=national credit API
#swagger.description=Sample Swagger implementation for the `test web api` service, leveraging annotations at the controller-method level.
#swagger.useDefaultResponseMessages=false
#swagger.enableUrlTemplating=false
#swagger.deepLinking=true
#swagger.defaultModelsExpandDepth=1
#swagger.defaultModelExpandDepth=1
#swagger.displayOperationId=false
#swagger.displayRequestDuration=false
#swagger.filter=false
#swagger.maxDisplayedTags=0
#swagger.showExtensions=false;