server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_URL:localhost}:5432/shar_db
    driver-class-name: org.postgresql.Driver
    username: rttr
    password: root
#  jpa:
#   generate-ddl: true
#   show-sql: true
#   hibernate:
#    ddl-auto: update

logging:
  file:
    name: log/logApp.log

auth:
  cookie:
    auth: AUTH-TOKEN
    refresh: REFRESH-TOKEN
    secret: ljhdsl;ghiopbmispvgspmvgjca;qdfs
    expiration-auth: 600000000
    expiration-refresh: 31536000
    path: /
#debug: false
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
