create table users_entity
(
    user_id int8 generated by default as identity,
    email   varchar(255),
    name    varchar(255),
    primary key (user_id)
);
create table words
(
    word_id     int8 generated by default as identity,
    description varchar(255),
    word        varchar(255),
    primary key (word_id)
);
create table word_user
(
    user_id int8 not null,
    word_id int8 not null
);