server:
  port: 8087

auth:
  cookie:
    auth: AUTH-TOKEN
    refresh: REFRESH-TOKEN

my:
  path:
    yml:
      urlname: http://${SPRING_DOCKER_URL:localhost}:8088/api/v1/auth/current

spring:
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_URL:localhost}:5400/shar_db2
    driver-class-name: org.postgresql.Driver
    username: rttr
    password: root
#  jpa:
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update

logging:
  file:
    name: log/logApp.log