version: '3'
services:
  db-rudenko-test:
    image: postgres:12
    restart: always
    ports:
    - 5444:5432
    environment:
     POSTGRES_PASSWORD: root
     POSTGRES_USER: rttr
     POSTGRES_DB: db_HW_1


